# Generated by Django 3.1.7 on 2021-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacotizacion', models.DateTimeField()),
                ('instalacion', models.BooleanField(default=True)),
                ('precioinstalacion', models.DecimalField(decimal_places=2, default=50.0, max_digits=1000)),
                ('preciocotizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
            ],
        ),
    ]
